### PR TITLE
Updating icons

### PR DESCRIPTION
**Pull request by bmignano**
## Description
* Updating icon page with new types and descriptions to include more use cases.

## Changes
* Added type and description for fa-ban
* ~~Updated type and description for fa-refresh to include two different use cases~~ Will be addressed in separate PR
* Added new pending icon as a variation of pficon-pending

### CODE REVIEW

**Comment by bmignano** [comment]
@mcarrano These recommendations came from a recent evaluation done on the OpenShift icon set. We found that some of the icons did not meet our needs for a variety of reasons and were hoping to add some alternatives or potentially reevaluate the recommended icons for certain cases. I've described each change in more detail below.

1. **fa-ban**: This icon already exists in the PatternFly icon library, but did not have a description. I've added a recommendation for the description outlining the use of this icon.

2. **fa-refresh**: The current icon PF recommends to use for On / Running (pficon-on-running) is also the exact logo for OLM. For this reason, we were not able to use this icon in OpenShift. We've used fa-refresh to represent 'Running' in past and have received positive feedback on using it for this case. Unsure if providing both icons for this use case makes sense or if we should potentially reevaluate the use of pficon-on-running for this.

3. **pficon-pending**: We've gotten feedback that it is hard to visually discern the hourglass inside a circle. We're aware that some products use icons in circles to represent status. Wondering if we can provide this alternative icon (without the circle) to products that don't use all the status icons. If approved, I'm happy to open a request to add this to the icon set, I wasn't sure how to go about this before!

I hope this clarifies the recommendations a bit. I'm definitely open to other ideas / feedback on these changes!

**Comment by mcarrano** [comment]
Thanks @bmignano This helps a lot.

I'm fine with adding the description to fa-ban. I'm also OK with adding the alternative for 'pficon-pending' as I can see how this is hard to resolve with the circle. But since we are using the hour-glass symbol in both cases, I don't see that as a problem. What you will need to do is to open an issue requesting to add this to the patternfly core distribution. The issue should be open in the 'patternfly' repo. You may also want to tag @rachael-phillips so she can line up a developer to do this. It's a very simple change to add an icon.

The one I'm on the fence about is using 'fa-refresh' to reflect a status of running. I totally understand why you can't use 'pficon-on-running', but I'm wary of using the same symbol to mean different things in different places. Have you considered whether 'pficon-on-running' can be redesigned to not conflict with a product logo? If you need to use 'fa-refresh' then I think I'd prefer to consider this a special case and just not document this on the website to keep a clear recommendation. Thoughts?

**Comment by serenamarie125** [comment]
hey @mcarrano curious about this 
> What you will need to do is to open an issue requesting to add this to the patternfly core distribution
If the icons are from the font awesome set, do we need to do this?

**Comment by bmignano** [comment]
Thanks @mcarrano and @serenamarie125 ! I removed the Running updates from this PR and opened an issue [here](https://github.com/patternfly/patternfly-design/issues/740). Let me know what else should be done to wrap up this PR.

**Comment by mcarrano** [comment]
Thanks, @bmignano That makes sense and I saw the other issue you opened. We can take that up separately. I will merge this.

@serenamarie125 as for adding the icon, perhaps I misunderstood, but it looked like this was a pf-icon (pficon-pending). If it's an fa icon that we are adding then you are right. No need to add it.

**Comment by serenamarie125** [comment]
Great work @bmignano & thanks for working with us on this one @mcarrano !

**Pull request merged**
