### PR TITLE
Updating Context Selector Images

### PR DESCRIPTION
**Pull request by jennyhaines**
@mcarrano @ncameronbritt 

## Description
* Updated the low fidelity mocks with high fidelity ones.  
* Adds onto this #321 Context Selector

### CODE REVIEW

**Comment by ncameronbritt** [comment]
LGTM

**Comment by LHinson** [comment]
@mcarrano @jennyhaines  should the responsive state also show the notification drawer icon?

**Comment by mcarrano** [comment]
Yes, good catch @LHinson . In that case the down-caret probably need to move to just after the menu item, right?

**Comment by LHinson** [comment]
I think so @mcarrano and show the bell icon. FYI @jennyhaines

**Comment by jennyhaines** [comment]
@LHinson - thanks for catching that! @ncameronbritt @mcarrano -

I just added a commit with the new image that includes that bell notification icon. Now that we have less space for the name, I was thinking about how we might want to truncate the name of the context if it is too long. I think it could be as simple as this: 
responsive-behavior-abbreviated

Would we want to specify this in the design specs?

**Comment by ncameronbritt** [comment]
LGTM

Fair question about truncation @jennyhaines. I don't think that issue is limited to mobile necessarily. I'm happy to think about this if we feel that something is needed beyond [PF's truncation recommendations](http://www.patternfly.org/styles/terminology-and-wording/#truncation).

**Comment by jennyhaines** [comment]
@ncameronbritt - aha! Good to know that we have documentation around truncation. I don't see a need to add it to the callouts, then!

**Comment by mcarrano** [comment]
Good catch regarding truncation. Maybe just add a reference and a link to the Truncation Guidelines? I think a mention of this is important, although I don't think you need a callout. The truncation could be end truncation as you show it or middle truncation depending on the nature of the item names in the menu.

**Comment by ncameronbritt** [comment]
@jennyhaines Do you want to just add this text to the end of the design.md page? 

```
### Truncation
Context names may need to be truncated if the names are very long, or if horizontal space is tight. Names should be truncated in a way that makes sense for the product or application. See PatternFly’s guidelines on [truncation](https://chrome.google.com/webstore/category/apps?hl=en-US).
```

**Comment by jennyhaines** [comment]
@mcarrano - sounds good to me- I just added that in. @ncameronbritt - Thanks for the wording!

**Comment by ncameronbritt** [comment]
@jennyhaines I included the wrong URL. Here's the correct one: http://www.patternfly.org/styles/terminology-and-wording/#truncation

**Comment by jennyhaines** [comment]
@ncameronbritt - It's fixed now. Thanks!

**Comment by LHinson** [comment]
Thanks for adding the bell icon @jennyhaines! Nice add with the truncation guidelines.

**Comment by mcarrano** [comment]
Looks great. I will merge.  Thanks @jennyhaines and @ncameronbritt !

**Pull request merged**
