### PR TITLE
Updating the bullet chart design pattern

### PR DESCRIPTION
**Pull request by bmignano**
## Description
Updating the bullet chart design pattern to match changes needed due to pattern implementation

JIRA: https://patternfly.atlassian.net/browse/OSUX-665

Closes: https://github.com/patternfly/patternfly-design/issues/662

## Changes

* Adding Measure Greater Than Max Range to Design page
* Editing Variations callout image on Overview page

## Contribution Submission Checklist

- [x] A GitHub issue was created and reviewed with the PatternFly community.
- [x] The pattern design overview.md and design.md templates were used to provide all information, relevant to this design.
- [x] Any new files have been added to the folder for that pattern.
- [x] The folder, for brand new patterns, has been titled with the name of the pattern.
- [x] All images are in an "img" folder and embedded images have the correct filepath.
- [x] The overview.md, design.md and site.md files, for this design have been commited and pushed to the patternfly-design repository, for review.

### CODE REVIEW

**Comment by bmignano** [comment]
@mcarrano Great catch! I accidentally reversed the callouts, my mistake. Will fix that and address your other comments once all the reviews are in. Thanks!

**Comment by bmignano** [comment]
Thought this was in pretty good shape overall so I went ahead and made @mcarrano 's changes. @beanh66 @serenamarie125 @mcarrano Please review!

**Comment by bmignano** [comment]
@mcarrano @beanh66 You both already approved, but I just had to make one small change – added a comma after the new jump link on the design page. Just waiting for review from @serenamarie125.

**Comment by mcarrano** [comment]
Thanks for reviewing @serenamarie125 . I will merge.

**Pull request merged**
