### PR TITLE
Forms - Advanced Options Revised

### PR DESCRIPTION
**Pull request by sjcox-rh**
New PR to update design page.  Combined callouts to match image and moved "Please note" text under callout two for Collapsed Section.

### CODE REVIEW

**Comment by sjcox-rh** [comment]
@andresgalante, @LHinson, @serenamarie125, please take a look at the updated PR which includes the revisions agreed upon.  Thanks!

**Comment by LHinson** [comment]
Awesome! LGTM @sjcox-rh 

Need a second review. @andresgalante or @serenamarie125 ?

**Comment by andresgalante** [comment]
👍 Thanks a lot @sjcox-rh Looks great.

@LHinson I am ok to merge it

**Comment by LHinson** [comment]
bitmoji

**Pull request merged**
