### PR TITLE
Add disabled state to Table View 

### PR DESCRIPTION
**Pull request by jryhanyc**
## Description
I've updated the Table View design.md file to show how to display disabled text in a table cell. 

[PTNFLY-2181](https://patternfly.atlassian.net/browse/PTNFLY-2181?filter=-1)

## Changes
* Updated PSD source file
* Updated table-callout1.png
* Updated table-callout2.png
* Updated Numbering to correspond with new PNG files
* Adjusted hierarchy of bullets, lists, etc. to make the design.md file easier to read

### CODE REVIEW

**Comment by jryhanyc** [comment]
@LHinson I noticed some numbering issues on the current [Table View](http://www.patternfly.org/pattern-library/content-views/table-view/#/api) page when I was adding the disabled text state. So, I adjusted in the new design.md file. 

Let me know if I need to clean up the new file. Thanks!

**Comment by maryclarke** [comment]
@serenamarie125 I guess I would prefer to see individual cells disabled when for whatever reason the content in that cell is not editable at this point in time, and for objects (whole rows) that are "disabled" or not applicable to be indicated by some type of status icon or indicator that could potentially provide more info to the end user about why that is the case.

**Comment by serenamarie125** [comment]
@maryclarke I agree with the suggested design for this use case, i think I'm wondering if we should really be calling it "disabled", because the data isn't really disabled, it's not available.  So my question is should we change the design documentation to call it something other than disabled. (hope that makes sense)

**Comment by LHinson** [comment]
Here is the use case the story resulted from: "The VM is currently off, so it cannot have any CPU usage." Therefore, "unavailable" makes sense to me. 

@serenamarie125 @maryclarke @catrobson @jryhanyc

**Comment by maryclarke** [comment]
I am good with "unavailable" @LHinson

**Comment by LHinson** [comment]
please review @serenamarie125

**Pull request merged**
