### PR TITLE
Update Masthead Utility Icons with Hover

### PR DESCRIPTION
**Pull request by yih-wang**
- Update hovered icons highlighted and with a background
- Update other icons in grey

### CODE REVIEW

**Comment by mcarrano** [comment]
@kybaker Please take a look at visuals for this. Thanks.

**Comment by kybaker** [comment]
@mcarrano @yih-wang Looks good.

**Comment by mcarrano** [comment]
Thanks @kybaker .  @LHinson can you give this a quick look and go ahead and merge if you don't see any issues.

**Comment by LHinson** [comment]
Thanks @yih-wang!

**Comment by mcarrano** [comment]
@LHinson and @kybaker , thanks for reviewing. I will go ahead and merge.

**Pull request merged**
