### PR TITLE
Adds newer icons to icons table, and adds content to fill blank spaces

### PR DESCRIPTION
**Pull request by jennyhaines**
## Changes

Write a list of changes this PR introduces

* Added the newer icons to be put into the table ("process-automation", "services", "integration", "filter", "enhancement", and "catalog") 
* Added a ton of content in the "Definition", "Type", and "Contextual Usage" columns. There used to be a lot of blank spaces. The only blank spaces that are left in these columns are because I couldn't answer them with 100% certainty.

### CODE REVIEW

**Comment by jennyhaines** [comment]
@andresgalante @LHinson - Do you think you could review this? Also, I'm not sure how to preview whether all of the icons will show up correctly. Andres, do you know how to check for this?

**Comment by LHinson** [comment]
Hey @jennyhaines! Thanks for sending this PR and taking the time to populate more of the table. Heads up that this is going to take some time to go through all of these to ensure all definitions are approved by stakeholders. @mcarrano is going to help with this effort. 

Are you ok waiting for a full review to introduce the 6 icons and definitions ("process-automation", "services", "integration", "filter", "enhancement", and "catalog")? The other option is to send a PR with those six and we can merge more quickly and take our time here. 

LMK!

**Comment by jennyhaines** [comment]
Hi @LHinson - I'm okay with waiting for the full review. I don't see a reason why it's imperative to have those six new ones in right away.

**Comment by LHinson** [comment]
Sounds good. Thanks @jennyhaines. We'll be in touch!

**Comment by mcarrano** [comment]
@jennyhaines @LHinson After some discussions with UXS's and others, I'd like to propose the following general updates to the way this table is defined and used:

* We should remove the 'Hex#' column as this is only meaningful for a handful of icons that use a default color. This information can be conveyed in the Contextual Usage column for those icons.
* The 'Definition' column should be used to convey the meaning of that icon when show in the UI. Some icons might take on multiple meanings depending on context so there might be multiple terms listed here. For example 'fa-angle-right' might mean Collapsed when used as part of an accordion or progressive disclosure control or Next when it appears in pagination.
* 'Type' is useful for grouping icons. I'd like to see us add the ability to search/filter on type. Looks like current type categories are Status, Object, Action, View, and Navigation. I don't think it makes sense for everything to be assigned a Type as some icons are just too general purpose (like the right arrow mentioned above) or we might add a 'General' category for these. Thoughts?
* The 'Contextual Usage' column is a good one to populate with more advise on how to use this icon in context (as you have done @jennyhaines ). We could also link to specific patterns for more info where appropriate. For example, since 'fa-bell' is primarily used in conjunction with notifications, it would be useful to link off to the Notifications Drawer pattern for more information on usage.

Let me know your thoughts on this and how to proceed. @jennyhaines I'm glad to collaborate with you on editing this content, although it's difficult to make item by item comments in its current form (i.e. as part of the PR). Perhaps we would be better editing in some type of shared doc and then uploading as part of a new PR? What do you both think?

**Comment by mcarrano** [comment]
p.s. I did see that I can open the table content inside the PR which would make row by row commenting more feasible. But again, let me know how you think we should proceed.

**Comment by jennyhaines** [comment]
@mcarrano - I really agree with each of your suggestions. The "Hex#" column is taking up so much space, so I like the idea of nixing it and putting any color recommendations in the Contextual Usage. I agree with your interpretations/usage of the "Definition", "Type", and "Contextual Usage" Columns, and also think there should be a "general" icon type for those icons that don't fit in the other boxes. 

I do think that for the "Definition" column, there might be some icons that actually can be used for two different reasons (like the fa-angle-right), so we might need to add a "/" between the different definitions.

In terms of how to edit everything, I like the idea of working in a Google Doc and uploading as a new PR. I think that seems a lot less tedious. I'll put that doc together and link to it in this PR once I'm finished.

**Comment by mcarrano** [comment]
Sounds great! Thanks @jennyhaines

**Comment by jennyhaines** [comment]
@LHinson @mcarrano - This is the Google Doc I put together to work on the table content! https://docs.google.com/spreadsheets/d/1uDRmqe9o91WazVetwevI0WEcVpZwO97MJZabqAouhE4/edit#gid=0

**Comment by mcarrano** [comment]
Thanks @jennyhaines this is very helpful. I will review and make comments directly in the document.

**Pull request closed without merging**
