### PR TITLE
Update Context Selector design docs for consistency with core impleme…

### LINKED ISSUE #569: Update Context Selector design docs for consistency with core implementation
During the process of implementing Context Selector, the design needed to be modified to consider responsive behaviors when shrinking viewport. The final implementation can be seen here: https://rawgit.com/matthewcarleton/patternfly/context-selector-dist/dist/tests/context-selector-vertical-nav.html

Overview.md and design.md pages should be updated for consistency.

### PR DESCRIPTION
**Pull request by zhutaoredhat**
Updated the all mockup images keep consistent with the implementation.

During the process of implementing Context Selector, the design needed to be modified to consider responsive behaviors when shrinking viewport. The final implementation can be seen here: https://rawgit.com/matthewcarleton/patternfly/context-selector-dist/dist/tests/context-selector-vertical-nav.html

Closes #569

### CODE REVIEW

**Comment by mcarrano** [comment]
@zhutaoredhat Thanks for sending this PR. @matthewcarleton can you also take a look at this? I think that we removed the option to have a label above the selected item name. (See callout 1). Is that right?

**Comment by matthewcarleton** [comment]
@mcarrano @zhutaoredhat this has actually changed slightly which you can see [here](https://github.com/patternfly/patternfly/pull/986). It brings it more inline with what other dropdowns look like.

**Comment by mcarrano** [comment]
There is a related issue here that we should resolve before merging this: https://github.com/patternfly/patternfly/issues/1006

**Comment by zhutaoredhat** [comment]
@mcarrano I had PTO last week. The vertical separator had been removed. Please have a review~
Request from : https://github.com/patternfly/patternfly/issues/1006

**Pull request merged**
