### PR TITLE
Updated breadcrumb images

### PR DESCRIPTION
**Pull request by kybaker**
Replaces breadcrumb images with high-fi. Closes: #414

### CODE REVIEW

**Comment by LHinson** [comment]
nice, this looks good to me. @mcarrano please merge if you agree. 

Thanks @kybaker !!

**Comment by kybaker** [comment]
@mcarrano I made the update to the switcher image. Please check and merge.

**Comment by LHinson** [comment]
Looks better @kybaker +1 from me.

**Comment by mcarrano** [comment]
Thanks, @kybaker . I am ready to merge.

**Pull request merged**
