### PR TITLE
Update the table with latest icons

### PR DESCRIPTION
**Pull request by junezhang**
## Description
* Update the table with latest icons  
* JIRA link: https://patternfly.atlassian.net/browse/PTNFLY-2535
* Github link: https://github.com/patternfly/patternfly/pull/716

## Changes
* Update the icons.md
* Add 11 new icons as following:

|Name   |Hex   |Content String   |Definition   |Type   |Contextual Usage   |
|---|---|---|---|---|---|
|pficon-applications   |   | e936  | Applications  | Object  |   |
|pficon-automation   |   |e937   |Automation   |   |   |
|pficon-connected   |   |e938   |Connected   |Status   | power is on and something is “up”. This is a more active alternative to “pficon-on”  |
|pficon-disconnected   |   |e939   |Disconnected   | Status  |power is off and something is “down”. This is a more active alternative to “pficon-off”   |
|pficon-infrastructure   |   |e93d   |Infrastructure   |   |   |
|pficon-optimize   |   |e93e   |Optimize   |   |   |
|pficon-orders   |   |e93f   |Orders   |   |   |
|pficon-plugged   |   |e930   | Plugged In  |Status   |x is currently restarting or rebooting   |
|pficon-service-catalog   |   |e941   |   |   |   |
|pficon-settings   |   |e610   |   |   |   |
|pficon-unplugged   |   |e942   | Unplugged  |Status   |x is disconnected, or "unplugged"   |

* Add the missing Content String as following

| Name  |Content String   |
|---|---|
|pficon-delete   | e611  |
|pficon-flag   | e603  |
|pficon-restart   | e617  |

## Screenshots for the udpate
icons1

@LHinson  please help to review.

### CODE REVIEW

**Comment by LHinson** [comment]
@junezhang thanks for providing a screenshot. This makes it easier for me to check! This PR looks good for the most part. Only two questions: 

- Why did you remove the unlocked icon? 
- The screenshot is clipped so I can verify if pficon-infrastructure is there. 

@serenamarie125 @jennyhaines Do we have approved definitions, content strings, etc that we can use to further populate the table?

**Comment by junezhang** [comment]
@LHinson nice catch. I re-send a commit about it and also re-update the screenshot about all icons.
Please have a review.

**Comment by jennyhaines** [comment]
@LHinson @junezhang @serenamarie125  -

I believe @andresgalante should know what the content strings are for the icons. He used a different process this time in generating and updating the font, so I think he has all of the metadata. 

Also I noticed that for some reason in the table "pficon-plugged" has the same definition and contextual usage and as pficon-pending. I would just delete out that current definition and contextual usage from "pficon-plugged" since it's in there in error.

As for populating the table, we don't have finalized definitions for anything more than what is populated, plus "pficon-restart", "pficon-plugged" and "pficon-unplugged". These are the Definitions, Icon Type, and Contextual Usage for those three:

**"pficon-restart"**
- Definition: Restarting
- Icon Type: Status
- Contextual Usage: x is currently restarting or rebooting

**"pficon-unplugged"**

**"pficon-plugged"**
- Definition: Plugged In
- Icon Type: Status
- Contextual Usage: x is connected, or "plugged in"

**"pficon-unplugged"**
- Definition: Unplugged
- Icon Type: Status
- Contextual Usage: x is disconnected, or "unplugged"

**Comment by junezhang** [comment]
@jennyhaines Thanks for your feedback. 
* The content string what i used is from this file: https://github.com/patternfly/patternfly/pull/716/files#diff-b0a36e20a3a1711ddb76656723ef535d
* Update the duplicate info between  pficon-plugged and pficon-pending
* Update the Definition and Type of pficon-restart/pficon-plugged/pficon-unplugged

@jennyhaines @LHinson  @serenamarie125 , Please have a review about it. I also updated the screenshots.

**Comment by LHinson** [comment]
LGTM! @jennyhaines once you give a thumbs up, I'll merge! Thanks @junezhang

**Comment by jennyhaines** [comment]
@junezhang @LHinson Nice- thanks! Everything looks good, except I see that the "connected" and "disconnected" icons are in, now!  I also have the Definition, Type, and Contextual Usage for those! If you could put these in, it's a thumbs-up from me! (Sorry about the piecemeal definitions.)

**"pficon-connected"**
Definition: Connected
Icon Type: Status
Contextual Usage: power is on and something is "up". This is a more active alternative to "pficon-on"
**"pficon-disconnected"**
Definition: Disconnected
Icon Type: Status
Contextual Usage: power is off and something is "down". This is a more active alternative to "pficon-off"

**Comment by junezhang** [comment]
@jennyhaines please have a review about the new patch about updating the definition of connect and disconnect icons.  also updated the icons screenshot.

**Comment by jennyhaines** [comment]
@junezhang - This looks good to me- thanks for the update!

**Comment by LHinson** [comment]
LGTM! Going to merge. Thanks @junezhang!

**Pull request merged**
