### PR TITLE
Added overview for horizontal navigation

### PR DESCRIPTION
**Pull request by jryhanyc**

### CODE REVIEW

**Comment by LHinson** [comment]
Woot, another designer sending a pull request!!! Awesome job @jryhanyc Thanks for joining us :) 

@andresgalante Will you help me review this one? @jryhanyc is just adding the overview .md for now. Will loop back around on the design .md as well as a small update to the overview .md to mention the sticky nav.

**Comment by andresgalante** [comment]
This looks great, thanks a lot @jryhanyc 
There is an issue with the path to the images I'll comment inline so you can see where. Also the page is missing a title.

**Comment by andresgalante** [comment]
Thanks @jryhanyc and sorry for my last comment I found the missing thing.

The PR has 2 `overview.md` :
- pattern-library/horizontal-navigation/design/overview.md
- pattern-library/navigation/horizontal-navigation/design/overview.md

One of them is wrong and shouldn't be on this PR. I am guessing the first one. Can you please remove it?

thanks a lot!

**Comment by jryhanyc** [comment]
@andresgalante thanks! I just removed the 1st instance: pattern-library/horizontal-navigation/design/overview.md

I had the fold structure setup incorrectly. Please let me know if this didn't come through correctly. thanks!

**Comment by andresgalante** [comment]
@jryhanyc Fantastic, thanks a lot!

@LHinson I am ok to merge it whenever you are ready

**Comment by LHinson** [comment]
This looks good @jryhanyc I'll go ahead and merge. Do you plan on sending another PR to include the details of the sticky nav?

**Comment by jryhanyc** [comment]
@LHinson I just sent another PR with the update

**Comment by LHinson** [comment]
Awesome! Thanks @jryhanyc.

**Pull request merged**
