### PR TITLE
Update the visual design of SSO Pattern

### PR DESCRIPTION
**Pull request by zhutaoredhat**
Updated all SSO mockups to visual design

### CODE REVIEW

**Comment by kybaker** [comment]
@zhutaoredhat I agree with @catrobson we can't ship these non Red Hat logos.

**Comment by mcarrano** [comment]
@matthewcarleton @LHinson and I have just been discussing this relative to a separate PR #512 that has been sent to update the design documentation to call out 3rd party logo usage guidelines. Let's come to a consensus on this. The third party logos are currently in the implementation so changes should be coordinated at this point. I can see both sides of the argument.

**Comment by matthewcarleton** [comment]
@kybaker is this an issue if we provide links to brand guidelines in the design docs?

**Comment by LHinson** [comment]
@kybaker @catrobson 

I have previously worked with Erin Champion in the legal department at Red Hat. She said that we can provide a devs the convenience of offering the image file....

> but it is up to the developer to ensure they obtain the proper written permissions from the respective trademark owners. I think it's safe to do as long as we include links to the policies so they will know the dos and donts as well as who they need to contact to get permission.

So we can deliver the SVGs as long as we include the links to the policies. I think PR #512 covers our bases. 

CC @mcarrano @matthewcarleton

**Comment by mcarrano** [comment]
@kybaker @catrobson Are you good to merge this now?

**Comment by mcarrano** [comment]
OK. I will merge this then.

**Pull request merged**
