### PR TITLE
Adding missing framework links for patterns to update design status page

### PR DESCRIPTION
**Pull request by amarie401**
## Description

This PR is a part of the Jira story below: 
https://patternfly.atlassian.net/browse/PTNFLY-2711

I have added the missing code links to the ```site.md``` for the different repo implementations that are available but not currently linked on pf-org. This would update the pf-org code tab and also update the design status page.

## Changes

Write a list of changes this design pattern introduces

* Changes to the ```site.md``` file

### CODE REVIEW

**Comment by amarie401** [comment]
@cliffpyles @mcarrano @LHinson could we get these reviewed soon?

**Comment by mcarrano** [comment]
So I just took a look at this @amarie401 . It's hard to test without staging the site, but I don't see any obvious problems. That said, I do have a question about the way the code is structured and how this is intended to work. I notice that you've replaced 'code' with 'code_html' in places, but them we also have 'impl_jquery' which I assume is a link to the core implementation? What does it mean when 'code_html' is false but there is a jQuery implementation?

**Comment by amarie401** [comment]
@mcarrano that's actually a good question.  In the places where I replaced ```code``` with ```code_html``` was for the cases where there are repo implementation examples available but no html pf-core example pointing to a ```code.md``` file in order to display it. If the code tab is set to false then the code tab is completely disabled which we don't want since we want to be able to show the links that are available for the other frameworks. So I set ```code_html``` to false so that it would enable the code tab and also display the message that there isn't a pf core example available and display the other framework links. When it comes to the design status page, it checks to see if there is a link associated with ```impl_jquery``` (which I made sure to include) so that should update accordingly.  

I also will be working on adding those html core examples that are missing on pf-org which will be a separate PR. Hope that answers your questions @mcarrano ? 

@cliffpyles could you check over these changes as well?

**Comment by amarie401** [comment]
@mcarrano that's a good question.  In the places where I replaced ```code: false``` with ```code_html: false``` was for the cases were there are framework implementation examples available but no pf-core html example available for a pattern (which would need a  ```code.md``` file in order to display it and it would be linked to ```code_html```). If the code tab is set to false then the code tab is completely disabled but we want to be able to show the links that are available for the other frameworks. So I set ```code_html``` to false so that it would enable the code tab and also display the message that there isn't a pf core example available while displaying the other framework links that are. 

When it comes to the design status page, it checks to see if there is a link associated with ```impl_jquery``` (which I made sure was included for those patterns available from the test pages) so that should update accordingly.  

I also will be working on adding those ```code.md``` files & pf-core examples that are missing on pf-org which will be a separate PR from a [Jira](https://patternfly.atlassian.net/browse/PTNFLY-2734?streamsSourceProduct=jira) story I created. Hope that answers your questions @mcarrano ? 

@cliffpyles could you check over these changes as well?

**Comment by mcarrano** [comment]
So given what you are saying @amarie401 . What will result from something like this? 

 overview: pattern-library/application-framework/single-sign-on/design/overview.md
 design: pattern-library/application-framework/single-sign-on/design/design.md
 code: false
+impl_jquery: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/login-single-sign-on.html

There is a core implementation as referenced here, however since 'code:false' we would not see it. Is that right or am I missing something?

**Comment by amarie401** [comment]
Yes, with ```code:false``` the tab is completely disabled so you wouldn't be able to see any example. ```impl_jquery``` is just a link to the test pages which is utilized by the design status page to provide a link to each example available for a specific pattern. What actually shows the core implementation/html example on the code tab is a ```code.md``` file that is linked to ```code_html``` 

For example using your reference:
```
overview: pattern-library/application-framework/single-sign-on/design/overview.md
design: pattern-library/application-framework/single-sign-on/design/design.md
-code: false (removing this line would then enable the code tab)
+code_html: pattern-library/application-framework/single-sign-on/code/code.md
 (adding this code.md file would then be used to display the core example)
+impl_jquery: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/login-single-sign-on.html
(this will be utilized by the design status page to link to the test page example)
```

Currently single sign on and a few others are missing on pf-org so I will have to create the missing ```code.md``` files for them in order to include and display them which will be my next steps moving forward. Hope this makes sense @mcarrano ! :)

**Comment by amarie401** [comment]
Yes, with ```code:false``` the tab is completely disabled so you wouldn't be able to see any example. ```impl_jquery``` is just a link to the test pages which is utilized by the design status page to provide a link to each example available for a pattern. What actually shows the core implementation/html example on the code tab is a ```code.md``` file that is linked to ```code_html```

For example using your reference:
```
overview: pattern-library/application-framework/single-sign-on/design/overview.md
design: pattern-library/application-framework/single-sign-on/design/design.md
-code: false (removing this line would then enable the code tab)
+code_html: code/application-framework/single-sign-on/code.md
 (adding this code.md file would then be used to display the core example)
*code_html: false (when there isn't a code.md (thus no pf core example available to display))
+impl_jquery: https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/login-single-sign-on.html
(this will be utilized by the design status page to link to the test page example)
```

Currently single sign on and a few others are missing on pf-org so I will have to create the missing ```code.md``` files for them in order to include and display them which will be my next steps moving forward. Hope this makes sense @mcarrano ! :)

**Comment by amarie401** [comment]
@cliffpyles could you review and check over these changes as well?

**Comment by mcarrano** [comment]
Thanks @amarie401 and @cliffpyles !

@LHinson if this looks good to you please go ahead and merge.

**Comment by amarie401** [comment]
This should be ready for a merge 👍

**Pull request merged**
