### PR TITLE
Experimental features

### PR DESCRIPTION
**Pull request by mindreeper2420**
## Description
This PR adds an Experimental Feature flag design pattern.

* https://github.com/fabric8-ui/fabric8-ux/issues/537
* https://github.com/patternfly/patternfly-design/issues/325

## Changes

* Adds a new Communication pattern

## New Pattern Checklist (if relevant)

- [X] Pattern does not already exist
- [X] Pattern solves common problems
- [ ] Pattern has community interest (You've addressed the PatternFly mailing list)
- [X] New files are in a folder titled with the name of the pattern
- [X] All images are in an "img" folder and embedded images have the correct file path
- [X] Both overview.md and design.md files are present

### CODE REVIEW

**Comment by Mgranfie** [comment]
@mindreeper2420  this is fantastic. Great idea and well documented.
 Few questions:
1. "Got it!: The "Got it!" text is a button link that is used to minimize the action bar."
What happens if I click on the Got it and I have not checked the agreement box? 
Do I get to use the feature anyway?

**Comment by Mgranfie** [comment]
2. "Optional: If you always want the bar to be displayed with the "This feature is experimental" text, you can remove the "More info" button and action."

If I want to cancel out of this, do I use the back button and or just navigate away from it?...

**Comment by Mgranfie** [comment]
3. More Info: The "More info" button is utilized to see additional information on the experimental feature that the user is attempting to utilize."
Where would this information display or would you imagine it navigates you somewhere else or this is a user based decision?

**Comment by Mgranfie** [comment]
@mindreeper2420 
Took a pass at clarification?..

"When the bar has been minimized, the flask button, in the upper right will remain visible. This will allow the user to access more information on the experimental feature (if applicable), at any time during the use of the feature."

**Comment by Mgranfie** [comment]
@mindreeper2420 took a shot at this text scrub?... Is this correct?

Icon: We utilize the flask icon to represent an experiment. The same icon is also used as a flag to show that either a page or a specific feature is considered experimental.

"This same icon can be used to indicate that a page or a feature is experimental."

**Comment by Mgranfie** [comment]
@mindreeper2420 Couple of curious questions...
1. Can this page address more than one experimental feature? 
2. Would there ever be more than one of these windows active at a time?

**Comment by mindreeper2420** [comment]
@Mgranfie I'll try to answer all of your questions in this one comment - please let me know if I missed any :-)

1. The "Got It!" text just applies to the information in the bar that you are currently looking at an experimental feature. By clicking on "Got It!", you are just shrinking the top border to the same width as the right, bottom and left borders, hiding the "This feature is experimental" text. A user will still need to accept the terms to use the feature.
  The concept of clicking "Got It!" came about in order to give users the vertical space back, if they so choose.

2. What I wrote is incorrect. It should be 
> Optional: If you always want the bar to be displayed with the "This feature is experimental" text, you can remove the "Git It!" button and action."

I will update the PR to reflect that.

3. Where and how the "More Info" is shown would be determined by the implementation of this design. In the current thought, it would bring a user to a new page (most likely in a new tab) so that the user would be able to quickly return to what they were looking for information on.

4. This page is designed to be the gateway to an experimental feature as a whole. Ideally, it would be applied to each individual experimental feature area, and not as a gateway to more than one experimental feature area. A product could have more than one of these areas active at a time, signifying that there are multiple experimental features for a user to use.

**Text clarification:** 
> When the bar has been minimized, the flask button, in the upper right will remain visible. This will allow the user to access more information on the experimental feature (if applicable), at any time during the use of the feature.

I like this text a lot better than what I have. I will replace what I have with this. Thanks!

> "This same icon can be used to indicate that a page or a feature is experimental."

Agree with this change. I will update this as well.

**Comment by mindreeper2420** [comment]
@Mgranfie I've updated the PR with the changes from our meeting.

**Comment by mindreeper2420** [comment]
@serenamarie125 I can see that being included - if the agreement checkbox is left optional, would the 'Activate' button just always be active upon first entering the screen?

**Comment by serenamarie125** [comment]
@mindreeper2420 After talking with Catherine, I think that having this mandatory makes sense from a best practices perspective!  OpenShift isn't currently doing this, but maybe we should be :)

**Comment by mcarrano** [comment]
Per UXS meeting 8/17-- Let's go with this for now (no further changes @mindreeper2420 ).  I will merge.

**Pull request merged**
