### PR TITLE
Pagination needs to point to the pattern library website, not github.

### PR DESCRIPTION
**Pull request by suzannehillman**
## Description
Pagination was pointing to github, not the pattern library website.

## Changes

Write a list of changes the PR introduces

*  Replaced the github link with http://www.patternfly.org/pattern-library/navigation/pagination/

### CODE REVIEW

**Comment by LHinson** [comment]
@suzannehillman would you mind also fixing "Table view" to say "Table View". All of our patterns should be capitalized.

**Comment by LHinson** [comment]
I'll go ahead and merge this one and file a bug for the capitalization error. Thanks @suzannehillman!

**Comment by suzannehillman** [comment]
Sorry, @LHinson: I'm rarely getting email about comments on bugs. I hadn't thought to check this one!

I'm going to go check why it's not emailing me most of the time.

**Comment by LHinson** [comment]
No worries @suzannehillman! Thanks for all your help!

**Pull request merged**
