### PR TITLE
Adding icon table

### PR DESCRIPTION
**Pull request by cshinn**
## Description
Adding the icons page to the styles page

This first version is missing several columns and only includes the icon itself and its name.

Because Github does not have our fonts installed, it will not correctly render the icons, but they should appear on patternfly.org when the page has been posted

## Changes

Adds icons.md

### CODE REVIEW

**Comment by LHinson** [comment]
Makes sense @cshinn Is that still correct that one will be able to copy the icon to their clipboard from this table?

**Comment by LHinson** [comment]
as well as this one.... appreciate all the help @cshinn!

**Comment by LHinson** [comment]
@cshinn do you know the answer to my above question?

**Comment by cshinn** [comment]
@LHinson I copied the icon code that the current website uses to display them. It is possible that there's some other magic going on in the background, but I'd expect this to behave the same way.

**Comment by LHinson** [comment]
ok thanks @cshinn

**Pull request merged**
