### PR TITLE
Initial support for syntax checking (linting) of markdown files.

### PR DESCRIPTION
**Pull request by bleathem**
## Description
I introduced a .editorconfig file to configure the editor of supported IDEs (Atom.io requires a plugin for this to work).

I Created a ruby Gemfile and setup the `npm run lint` command to run _markdownlint_ and report any makrdown syntax errors.

To test this PR, run:
```
npm run bundle
npm run lint
```

### CODE REVIEW

**Comment by cshinn** [comment]
@bleathem downloaded and ran and it looks like the linter is working great. Got an angry looking npm error message at the end, but I assume that was a result of the linter kicking back a failure and not anything more severe, but I thought I'd mention it anyway. Looks good!

**Comment by bleathem** [comment]
Yep, the linter exits with an error code if it finds a rule is broken.  This is a good thing, as it's how travis will report the error when we enable the lint check on travis.  Thanks for trying it out @cshinn !

**Comment by cshinn** [comment]
@bleathem out of curiosity, what are those rules that you had it ignore?

**Comment by bleathem** [comment]
@cshinn to answer your question, I added a comment where the rules excluded/configured are explained via a comment

**Comment by cshinn** [comment]
@bleathem excellent! LGTM

**Pull request merged**
