### PR TITLE
Split the icons file in two, remove the icons zip file

### PR DESCRIPTION
**Pull request by bleathem**
## Description
This PR splits the icons.md file into two files, so they are easier to include in the site as side-by-side columns.

I also removed the out-of-date patternfly icons zip file.  If we wish to distribute the icons as a zip we can include it as a patternfly build step, and link to the distribution from the docs.  The file located here would be difficult to keep up-to-date.

A stage of the site using the files of this PR for content can be viewed here:
https://bleathem.github.io/patternfly-org/styles/icons/

### CODE REVIEW

**Comment by bleathem** [comment]
Nice catch @serenamarie125!  I've updated the table to use names for both.  We can add a description column in a follow-up PR

**Comment by jennyhaines** [comment]
+1

**Comment by andresgalante** [comment]
👍  😄

**Comment by LHinson** [comment]
+1 bitmoji

**Pull request merged**
