### PR TITLE
New Updates for Sort

### PR DESCRIPTION
**Pull request by yih-wang**
- Add a definition of class to table in the source code

### CODE REVIEW

**Comment by yih-wang** [comment]
@LHinson @mcarrano Fixed the problem! Please review it, thank you.

**Comment by mcarrano** [comment]
@yih-wang  When I view this in GitHub, there still seems to be a problem.  The icons no longer show up.  There is also some extra text.
screen shot 2017-04-25 at 11 31 02 am  See the attached screen shot.

**Comment by LHinson** [comment]
@mcarrano I think the icons should display on the site but won't preview in GitHub

**Comment by mcarrano** [comment]
OK.  I am going to merge then to see what happens!

**Comment by mcarrano** [comment]
Still does not look right.  @LHinson Who created the table for the Toolbar pattern?  Was it @cshinn ? I have no idea why @yih-wang 's changes don't work.

**Comment by yih-wang** [comment]
@mcarrano @LHinson I compared the two source code in PatternFly and found my previous code missing a class definition in the <table> tag. So I added the extra text (the class definition) at the end of the table in this version, just like the MD file of Tooltip. I have no idea why the class definition still doesn't show up in source code in PatternFly. Maybe some extra code is needed beyond the MD file?

**Comment by LHinson** [comment]
@bleathem @andresgalante or @jgiardino, can you help with this one?

**Pull request merged**
