### PR TITLE
updated icomoon.md to include new icons, definitions, type and example

### PR DESCRIPTION
**Pull request by LHinson**
updated icomoon to include new icons, definitions, type and example. 

Please note:
* This is only for pf icons. fa icons are a separate file/table.
* pficon-replicator, pficon-connected and pficon-disconnected are missing and require some investigation. 
* These icons do not have color. That is not in scope for this story. 
* there are some missing content strings that need to be populated. 

@serenamarie125 @mcarrano @Mgranfie @andresgalante

### CODE REVIEW

**Comment by serenamarie125** [comment]
@LHinson this is looking good.

Are you looking for content strings before this PR is merged, or can that be done iteratively?

Eventually, this should be one table, as the most important item will be looking for definition, not the actual icon name.

**Comment by LHinson** [comment]
@serenamarie125 I'm ok with addressing the additional things such as the content strings in another PR. 

@bleathem any technical reason these icons tables are separate?

**Comment by jennyhaines** [comment]
@LHinson - The reason that "pficon-connected" and "pficon-disconnected" are not showing up is because these icons were created after Andres updated the PatternFly font. for these to display, I would need to send Andres the files/information for these two icons, and he would need to make another update to the PatternFly font  As for "pficon-replicator", it's content string is "e624". Maybe the wrong content string is in there.

**Comment by Mgranfie** [comment]
This is looking good! I agree that the definitions and the images become
the most useful content....

**Comment by mcarrano** [comment]
@LHinson can you provide some more background on the scope of this change and what we should be reviewing? I don't see any problem with the related files, but also not sure what I am looking for. @serenamarie125 I think we do have a separate issue identified around providing more info about usage. See https://github.com/patternfly/patternfly-design/issues/308

**Comment by LHinson** [comment]
@mcarrano  This PR adds the following columns: Type, Definition and Contextual Usage. This does start to address #308 

Based on Brian's previous icon page design here: https://drive.google.com/file/d/0BwL_r77doqY_aWxIOXlBRC1MZGM/view

@bleathem has updated the icon page so that the tables stack vs side by side to allow the space for this table. I will need to sync with him regarding mixing font awesome and pf-icon into one table.

**Comment by Mgranfie** [comment]
This is fantastic!! My only question is around the file format. Was there
any discussion about providing an .svg over a .png?....

**Comment by LHinson** [comment]
"You can also download the set of PatternFly icon SVGs." is currently on the site. This allows you to download a zipped file. See: http://www.patternfly.org/styles/icons/ Do we want to individually download each icon? 

There is no technical reason why we can't combine the font awesome and pf-icons. I'll make a separate story so it doesn't hold this PR up. FYI @serenamarie125

**Comment by Mgranfie** [comment]
Ah OK... good question.... maybe not? Not sure which is preferred, so maybe
not too important right now then :)

**Comment by Mgranfie** [comment]
LGTM!

**Pull request merged**
