### PR TITLE
Remove WC and CSS tables, jQuery to Core, and 2+ to 4+

### PR DESCRIPTION
**Pull request by amarie401**
## Description
This PR introduces the removal of the WC and CSS table on the design status page, changes jquery to core, and ng 2+ to 4+ as related to this jira story: https://patternfly.atlassian.net/browse/PTNFLY-2712

## Changes

Write a list of changes this design pattern introduces

* Removal of WC and CSS
* jQuery to Core
* Ng 2+ to 4+

### CODE REVIEW

**Comment by LHinson** [comment]
@amarie401 would you be able to attach a screenshot so I can review that way?

**Comment by amarie401** [comment]
@cliffpyles I am getting errors running ```npm serve``` for this repo. I am trying to test the design status page updates that I made.

**Comment by LHinson** [comment]
@amarie401 usually I just use the "View" button under the "Files Changed" section and it will show me a view of the .md. Unfortunately this a different thing though so can't review it in the same way. 

I'm OK with just two dev reviews (if they can do so without preview) if that is easiest. Let's wait for @cliffpyles to advise.

**Comment by amarie401** [comment]
Thanks @cliffpyles, @dabeng @michael-coker could either of you review as well for another dev review?

**Comment by cliffpyles** [comment]
To review a folder has to be created in the project root first.

You can get the build to work by running:

- `mkdir -p publish/status`
- `npm run bundle`
- `npm run build-status`
- `npm run serve` (to start the server)

**Comment by amarie401** [comment]
Thanks a ton! @cliffpyles 

@LHinson Screenshot:

screen shot 2018-02-05 at 4 02 14 pm

**Comment by LHinson** [comment]
Awesome! Go ahead and merge @cliffpyles

**Pull request merged**
