### PR TITLE
Draft of Help story pages

### PR DESCRIPTION
**Pull request by bkjeffer**
## Description
Pages for the new Help section describing syntax hints and field level help

### CODE REVIEW

**Comment by mcarrano** [comment]
@bkjeffer Thanks for submitting this PR. We will review and get back to you shortly with feedback.

**Comment by mcarrano** [comment]
@bkjeffer I discussed this PR with @LHinson and we decided that if you can just make a quick update to change the name of this from "Help" to "Help on Forms" we can go ahead and merge.  An issue will then be filed for any further follow-up on visual styling.  Let us know if you are OK with that.

**Comment by bkjeffer** [comment]
@mcarrano I can make that update.

**Comment by LHinson** [comment]
Thanks @bkjeffer Going to merge this one!

**Comment by mcarrano** [comment]
@LHinson This is not yet showing up on the site.  Possibly missing a site.md file? How should we handle?

**Comment by LHinson** [comment]
Correct, it needs to have a design folder (with the design.md and overview.md inside of it) + the site.md

I can see that missing here: https://github.com/patternfly/patternfly-design/tree/master/pattern-library/forms-and-controls/help-on-forms/design

**Pull request merged**
