### PR TITLE
Changes Close (X) button in expanded list panel to optional

### PR DESCRIPTION
**Pull request by mcarrano**
## Description
This change is in response to PF-react issue https://github.com/patternfly/patternfly-react/issues/153. As highlighted in this issue, there are cases where the presence of this button can interfere with other content on this page, and in my judgement, while it is nice to have, it is not required for closing the expanded list item. This can be easily accomplished by single clicking on the expanded row.

## Changes

Write a list of changes this design pattern introduces

* Change the text in design.md to make the Close button optional.

## Contribution Submission Checklist

- [ ] A GitHub issue was created and reviewed with the PatternFly community.
- [ ] The pattern design overview.md and design.md templates were used to provide all information, relevant to this design.
- [ ] Any new files have been added to the folder for that pattern.
- [ ] The folder, for brand new patterns, has been titled with the name of the pattern.
- [ ] All images are in an "img" folder and embedded images have the correct filepath.
- [x ] The overview.md, design.md and site.md files, for this design have been commited and pushed to the patternfly-design repository, for review.

### CODE REVIEW

**Comment by mcarrano** [comment]
@LHinson if needed, I can give more background on this. But it seems like a simple and obvious change so I decided to go straight to sending this PR to make the update. Please review when you get a chance.

**Comment by LHinson** [comment]
This looks good except "Optional" should not be in bold

**Comment by mcarrano** [comment]
@LHinson I've updated to change "optional" to not be bold. Please review again and merge if you are OK with this.

**Comment by LHinson** [comment]
Great, I'll merge once checks have passed. Thanks @mcarrano

**Comment by mcarrano** [comment]
Looks like there are conflicts @LHinson . Do you know how to resolve? I may need to get some help.

**Comment by LHinson** [comment]
@mcarrano either requires a rebase or you could copy the changes from here, pull down again and open another PR.

**Comment by LHinson** [comment]
bitmoji

**Pull request merged**
