### PR TITLE
Fly Out Secondary Navigation Updates

### PR DESCRIPTION
**Pull request by yih-wang**
Replace the current wireframes for Flyout Secondary Navigation in the
Vertical Navigation with high-fidelity mockups.

### CODE REVIEW

**Comment by mcarrano** [comment]
One more thing @yih-wang.  We want to start keeping source files for mockups with other pattern content on the repo.  Can you please upload your source file for this mockup to a /documents folder in the root directory for this pattern.  See https://github.com/patternfly/patternfly-design/wiki for more details on the intended structure.

**Comment by yih-wang** [comment]
@mcarrano Updated the image and uploaded the source file to the new folder, please check it.

**Comment by mcarrano** [comment]
This looks great, @yih-wang .  @LHinson if you are good with this, please go ahead and merge.

**Comment by LHinson** [comment]
Yes, very good. I will merge now.

**Pull request merged**
