### PR TITLE
Adding the Angular PatternFly Community Meeting Slides as a PDF

### PR DESCRIPTION
**Pull request by beanh66**
## Description
- Created a folder for the Angular Repo, under Resources/Community
- Added the Angular Community Meeting Slides as a PDF 

@LHinson Please take a look!

### CODE REVIEW

**Comment by Mgranfie** [comment]
@beanh66 just curious on the minutes for this re: those using Angular 4 and if they plan to use NG... anything on this you can share with us?

**Comment by beanh66** [comment]
@Mgranfie Yep! I'm trying to get these slides posted here so I can reference the link when I post to the PatternFly org repo. I'll be posting the recording along with the slides though so you will be able to see both from here: http://www.patternfly.org/community/monthly-community-meeting/

**Comment by LHinson** [comment]
Thanks @beanh66! One minor issue is with the file name. [For technical reasons](https://superuser.com/questions/29111/what-technical-reasons-exist-for-not-using-space-characters-in-file-names), please use all lower case, no spaces and dashes (-) instead. 

Thanks and apologies for not catching that up front!

**Comment by LHinson** [comment]
bitmoji

**Pull request merged**
