### PR TITLE
Contribution: Empty State Cards

### PR DESCRIPTION
**Pull request by mindreeper2420**
## Description
This is a contribution from OSIO for an Empty State Card component. This Card is primarily used on Dashboards.

## Changes

* New Empty State Card design

## New Pattern Checklist (if relevant)

- [X] Pattern does not already exist
- [X] Pattern solves common problems
- [ ] Pattern has community interest (You've addressed the PatternFly mailing list)
- [X] New files are in a folder titled with the name of the pattern
- [X] All images are in an "img" folder and embedded images have the correct filepath
- [X] Both overview.md and design.md files are present

### CODE REVIEW

**Comment by serenamarie125** [comment]
@mindreeper2420 have you seen the content here ? http://www.patternfly.org/pattern-library/cards/base-card/#/design  

It seems like your proposed designs conflict with some of the things we already have defined?

**Comment by mindreeper2420** [comment]
@serenamarie125 I have seen that. The only conflict that I can see is in the 'No Data Available' Card. This is an extension of that (as users in OSIO found it to be too uninformative to be useful).

The 'Empty State Card with Primary Action' is meant to provide users with information that they might find useful, but also allow them the ability to quickly perform an action that remedies that empty state. This follows the pattern of the existing Empty State but just adds it inside of the Card. The moving of the Actions Panel to the top right is so that less vertical space is taken up by a single button, and provides an interaction that is consistently in place when data is present in the card.

Would it make more sense to submit this as an improvement of the 'No Data Available' Card, rather two new cards?

**Comment by serenamarie125** [comment]
@mindreeper2420 I was more thinking about the fact that the page i referenced shows actions in the bottom panel, but you are showing the + in the top right, and then buttons in the content. 

I definitely like the extension to show additional information, but I would suggest that it is a sub heading within the Base Card, right above No Data Available.  (but that is just my opinion)

I'm curious as to what visuals would suggest - whether adding buttons inside as the empty state panel of a page, or adding the actions in the Actions Panel itself, which is part of the base card.

**Comment by mindreeper2420** [comment]
@serenamarie125 I think the additional information as a sub heading is a good one - keeping the 'No Data Available' as the last line of text.

We thought quite a bit about deviating from the Action Panel designs, and came up with moving the action item (in this case, the +) to the top right due the fact that it keeps a consistent "quick action" piece available at all times (whether data is present in the card or not), but also allows more vertical space for the content inside of the card. We (OSIO) commonly has lists inside of the cards (another deviation from PatternFly), where the bottom Action Panel is essentially another row of data that can be displayed.

**Comment by mcarrano** [comment]
Agree with @serenamarie125 comment about including this detail as part of the Base Card pattern rather than defining a new pattern.  Basically this could be applied against any card when there is no data to show, right? @LHinson what are your thoughts?

@mindreeper2420 I agree with your points about why the actions make sense in the top right.  We have some internal inconsistencies here that I think we need to resolve.

**Comment by LHinson** [comment]
Thanks for contributing @mindreeper2420! 

@mcarrano @serenamarie125 shouldn't @mindreeper2420 or any other product be able to construct the card in a way that makes sense for their use cases? There is some good thought that went into WHY they were placed there. I don't know that we really can be that prescriptive about where actions go. I'm ok with the discrepancy as I think PatternFly should be flexible and modular. I do think we should clarify this somewhere though.

**Comment by mcarrano** [comment]
@LHinson yes, I do think that projects should have latitude to customize card layout in a way that makes sense according to their unique requirements.  My concern is more internal consistency within PatternFly.  If in one place we say actions should go in the top right and another in the bottom right, it creates confusion for those trying to follow the standard.  It may be a question of what things need to be standardized and what is left for designers to find the best solution according to their project needs.  It seems like placement of actions is something that we should be able to standardize or at least provide multiple options and criteria for making choices, similar to how we present the Toolbar.  Do you agree?

**Pull request closed without merging**
