### PR TITLE
Add donut chart pattern

### PR DESCRIPTION
**Pull request by serenamarie125**
Add the pattern as it currently exists on patternfly.org

### CODE REVIEW

**Comment by andresgalante** [comment]
Links are broken, we can't use relative addresses.

**Comment by serenamarie125** [comment]
@andresgalante please take a look - I think I've done it correctly.  These links are anchors to this page, so I don't think i need the full URL.  Thanks!

**Comment by LHinson** [comment]
Links are working for me. @cshinn will you also review and merge if it looks good?

**Comment by cshinn** [comment]
Looks good to me. I'm not sure exactly how we will want to format anchor tags for uploading to the site, but that's an issue across patterns, not just this one.

**Pull request merged**
