### PR TITLE
separate icon data from presentation

### LINKED ISSUE #674: Icons Table: pficon-enhancement cannot be copied to the clipboard
There is a bug in the Icons table http://www.patternfly.org/styles/icons/ that is preventing the pficon-enhancement to be copied to the clipboard. See https://github.com/patternfly/patternfly-org/issues/575 for more info.

### PR DESCRIPTION
**Pull request by michpetrov**
## Description
* Moved the icon data to a JSON file, changed the original file to generate the icon table from those data. Also added content strings for the FontAwesome icons which were missing.
* Tweaking the build process of patternfly-org is required for this to take effect.
* Fixes #674

### CODE REVIEW

**Comment by mcarrano** [comment]
@michpetrov Thanks for proposing this change. I definitely think that moving the icon data to a JSON file will make it easier to maintain. But before we merge, I'd like @amarie401 @dgutride and @LHinson to review and make sure they are good with this approach. Do any of you see potential issues with this?

Note that there is a corresponding PR in patternfly-org https://github.com/patternfly/patternfly-org/pull/576

**Comment by amarie401** [comment]
I have no issue with adding the icon data as JSON (we do this already with the entire pattern library), in fact this is a good choice in terms of maintainability as you already noted @mcarrano. @dgutride if this looks good to you also then I say let's go with this approach.

**Comment by LHinson** [comment]
LGTM! Thanks for your continually helping us out @michpetrov!

**Comment by amarie401** [comment]
Thanks for contributing this @michpetrov ! 👍

**Comment by amarie401** [comment]
Going to go ahead and merge this one

**Pull request merged**
