### PR TITLE
Responsive State for Notification Drawer

### PR DESCRIPTION
**Pull request by yih-wang**
Redesign of the responsive state for notification drawer

### CODE REVIEW

**Comment by LHinson** [comment]
@mcarrano @yih-wang I'm going to go ahead and merge this one but have some additional questions / comments on the general pattern we can address later... 

- What happens if you have the notification drawer open, then open the navigation? Does the notification drawer auto collapse or do they layer? 
- I like that addition of explaining the difference in icons. I think that need to be listed above. Not sure that we need to list twice. The callouts under the mobile section can be very specific to the responsive behavior instead of repeating. 
- Toast notification image needs to be reduced down to 72px
- Drawer Title with the explanation "Drawer Title" is not all that helpful.

**Comment by LHinson** [comment]
I've added an issue FYI @mcarrano https://github.com/patternfly/patternfly-design/issues/279

**Comment by lizsurette** [comment]
@yih-wang I think this looks great. The only comment I have is about the blue icon when the drawer is open. I like it, but it's inconsistent with the non-mobile version. @LHinson do you think we should file an issue to think about this further?

**Comment by LHinson** [comment]
Make sense @lizsurette. I just added your comment to the #279 issue that I already filed so that all concerns can be addressed at once time hopefully.

**Pull request merged**
