### PR TITLE
Update classified/unclassified color associations

### PR DESCRIPTION
**Pull request by shawndwells**
## Description
Unclassified should be green, classified should be red.

### CODE REVIEW

**Comment by mcarrano** [comment]
If this is the case @shawndwells , it means that the images are incorrect, also. Classified is shown with a green banner. Can the images be redone?

**Comment by shawndwells** [comment]
@mcarrano thanks for the review!

At first glance the images do appear to say ``CLASSIFIED``, but the images use generic text ``CLASSIFIER``.

For example, the green banner:
https://www.patternfly.org/pattern-library/communication/classification-banner/img/green.png

And red:
https://www.patternfly.org/pattern-library/communication/classification-banner/img/red_screen.png

**Comment by mcarrano** [comment]
Ah, I see @shawndwells . It is pretty easy to miss that. But I'm OK with that if you think it will be clear to the people using this. Does the design.md page also need updating. Looks like the color descriptions are also swapped there. See the table under Classification Level.

**Comment by shawndwells** [comment]
On colors, yes, it would meet market (incl non-Gov) expectations. For example, from another project:

image

(or a longer thread about the color history at https://security.stackexchange.com/questions/161829/do-us-classification-levels-have-official-color-values)

For the ``design.md``, created PR https://github.com/patternfly/patternfly-design/pull/746

**Comment by shawndwells** [comment]
Bit further description -- essentially, green is associated with unclassified. Anything non-green is classified.

**Comment by redhatrises** [comment]
> Ah, I see @shawndwells . It is pretty easy to miss that. But I'm OK with that if you think it will be clear to the people using this. Does the design.md page also need updating. Looks like the color descriptions are also swapped there. See the table under Classification Level.

@mcarrano @shawndwells submitted a separate PR to fix those. See #746

**Comment by redhatrises** [comment]
@mcarrano since #746 was merged, can this be merged as well or is there something else that needs to be done?

**Comment by shawndwells** [comment]
I'm back from PTO. Let me know if any updates are required!

**Pull request merged**
