### PR TITLE
Icon Table Update 

### PR DESCRIPTION
**Pull request by LHinson**
* Consolidated the fa and pf icons table
* Add a column for hex # (to be populated once we have that information)
* Added definitions and usage example for fa icons that have been agreed upon

@serenamarie125 @jennyhaines @mcarrano @Mgranfie

### CODE REVIEW

**Comment by LHinson** [comment]
@serenamarie125 @mcarrano any concerns with this PR?

**Comment by jennyhaines** [comment]
I think these are great updates! No concerns @LHinson

**Comment by serenamarie125** [comment]
I'm unsure how to view this appropriately, can someone help me out @LHinson

**Comment by LHinson** [comment]
@serenamarie125 I realize the preview of the PR is not allowing you to see the icons. I’m going to just merge this so you can view it via the site and I’ll commit to making any critical updates immediately. This does require one update from @bleathem so I'll work with him on that and let you know when the table is live.

**Comment by Mgranfie** [comment]
Edit verbiage on icon from "Ellipsis" to "Ellipses" @LHinson ....

**Comment by LHinson** [comment]
@Mgranfie After looking into this, I determined that it should remain "Ellipsis" for the following reasons: 

* This is a font awesome icon. Font awesome defines this as "Ellipsis"
* The Cambridge Guide to English Usage says this: _Both grammarians and editors make use of this term. In grammar, ellipsis means the omission of a word or words which would complete or clarify the sentence._

**Comment by Mgranfie** [comment]
Sounds good!

**Pull request merged**
