### PR TITLE
Switching out the low fidelity Slider images for high fidelity images

### PR DESCRIPTION
**Pull request by jennyhaines**
## Description
* This addresses #334 , the need for high-fidelity visuals.

@mcarrano @serenamarie125 @beanh66 @kybaker

### CODE REVIEW

**Comment by jennyhaines** [comment]
It looked good to begin with, but made sure to use high fidelity components and PatternFly text sizing/coloring to pull this together. I also didn't see the need for a blue slider handle. I kept it neutral so that the only element that would ever be blue is the bar.

**Comment by beanh66** [comment]
LGTM @jennyhaines

**Comment by kybaker** [comment]
@jennyhaines Very nice work.

**Comment by mcarrano** [comment]
Thanks, @jennyhaines . Works for me. @serenamarie125 can you take a quick look? If you are good I will merge.

**Pull request merged**
