### PR TITLE
Update the info icon to PatternFly Icon

### PR DESCRIPTION
**Pull request by junezhang**
## Description
* Icon on field level help should be pficon-info
http://www.patternfly.org/pattern-library/forms-and-controls/field-level-help/#_ 
* JIRA link: https://patternfly.atlassian.net/browse/PTNFLY-2124

## Changes
* Update the Field-Level-Help design.md
* Update the two pictures related the info-icon

## Contribution Submission Checklist

- [x] A GitHub issue was created and reviewed with the PatternFly community.
- [x] The pattern design overview.md and design.md templates were used to provide all information, relevant to this design.
- [ ] Any new files have been added to the folder for that pattern.
- [x] The folder, for brand new patterns, has been titled with the name of the pattern.
- [x] All images are in an "img" folder and embedded images have the correct filepath.
- [x] The overview.md and design.md, for this design have been commited and pushed to the patternfly-design repository, for review.

### CODE REVIEW

**Comment by LHinson** [comment]
LGTM! @junezhang do you mind filing an issue against the patternfly repo in order to update the implementation. 

@mcarrano if you approve, please merge!

**Comment by junezhang** [comment]
@LHinson Sure thing, I'm going to do the code part to update the implementation.

**Comment by LHinson** [comment]
Fantastic @junezhang

**Comment by mcarrano** [comment]
Looks good.  Thanks @junezhang ! I will merge.

**Pull request merged**
