### PR TITLE
Update List View Design with Light Blue Hover State

### PR DESCRIPTION
**Pull request by zhutaoredhat**
https://github.com/patternfly/patternfly-design/issues/314
There are two mockups need to be updated to light blue hover state

### CODE REVIEW

**Comment by mcarrano** [comment]
@zhutaoredhat The hover color and the selected color should be slightly different. Selected is same as before and hover is slightly lighter. From your mockups, looks like you have them all the same. Check with @jennyhaines if you need exact RGB values for these. I'm actually wondering if we should call out the color values in the design documentation. @LHinson and @kybaker , what do you think?

**Comment by jennyhaines** [comment]
@zhutaoredhat - The hex for that hover state light blue is #edf8ff , and the hex for the selected state is #def3ff. It's only a slight color difference- this image shows you the difference: 
colors

**Comment by zhutaoredhat** [comment]
Hi @mcarrano I had updated a new commit. 
In the commit 1, the Selected is same as before and just changed the hover is slightly lighter to #edf8ff. 
In the commit 2, updated the selected color to #def3ff.
Hi @jennyhaines Please help me have a review either. Thank you~

(ps:I think when the selected state and hover state are not together, it will be harder to distinguish the difference between these two color.)

**Comment by jennyhaines** [comment]
@zhutaoredhat - I think this looks good- thanks! I don't know that it is actually a big deal that the colors are similar, especially because as the user interacts with the list view items, they learn that the color only temporarily changes during hover. I don't want to make the hover any lighter because if it's too light, it might not show up on certain monitors.

**Comment by mcarrano** [comment]
I agree with @jennyhaines . The purpose of the hover is to just reflect that an item is clickable. Since it's not a static state, I'm ok that the two colors are similar. The user just need to see some visual change on mouse in/out.

**Comment by zhutaoredhat** [comment]
@jennyhaines @mcarrano That's cool!~ Great thanks.

**Comment by mcarrano** [comment]
I think we are all set with this one. I will merge. Thanks for your effort, @zhutaoredhat !

**Pull request merged**
