### PR TITLE
Update the visual design of login pattern

### PR DESCRIPTION
**Pull request by zhutaoredhat**
Updated Login Page mockups to visual design

### CODE REVIEW

**Comment by zhutaoredhat** [comment]
Hi @mcarrano @yih-wang great job! I have updated the all mockups to visual design. When I was creating the visual design for them, I thought there are some new updates maybe make this PR better.
1. In the overview page, whether we can use the design with 4 third-party accounts. I think it is enough for most application and we encourage the developer to choose the top 4 used accounts for users . More than 8 third-party accounts is made for keycloak. Dose it make sense to remove that part for the PatternFly design.
2.The design document dosen't include the method about "Social account first". https://redhat.invisionapp.com/share/2DE6FA656#/255230620_8
it is popular today either. How about we create a new section called "Social account login" with the two kinds of social account login.
3.About Error Messages, the rules are complex to me. The more we write, the less will user get. PatternFly is not a popular science website, it dosen't need include all kinds of validation. Just some simple and friendly interaction will be better to me.
These are some of my immature thoughts. Welcome feedbacks~

**Comment by kybaker** [comment]
@zhutaoredhat Agree with @catrobson here. Please update the link colors. Other than that it looks good.

**Comment by zhutaoredhat** [comment]
@catrobson @kybaker Thanks for your feedback~ I have updated them all and pulled a new request. Please have a review~

**Comment by matthewcarleton** [comment]
@mcarrano @zhutaoredhat currently if you add more than eight options it will just continue to grow in height. I agree that if there is a show button it should remain but be swapped out for "Hide" when expanded. We will have to loop in a JS resource for this though.

**Comment by serenamarie125** [comment]
@catrobson this is a nit, but I'm pretty sure that we try to omit "Please" in prompts to try and keep things as concise as possible.

**Comment by catrobson** [comment]
@serenamarie125 that's fine with me.  "Enter a valid email address" would work for me then, thanks for the correction.  I think I saw a few other "please" messages in the validation so we might need to do another glance at the message content.

**Comment by mcarrano** [comment]
@zhutaoredhat @matthewcarleton For expanding or collapsing the social login grid, instead of a button, how about something more like this: 
social login
The more link only displays when there are more than eight items and changes to 'Less ^' when the panel is expanded. Thoughts?

**Comment by matthewcarleton** [comment]
@mcarrano that makes sense to me. Should we match the design of the carot to the language switcher or possibly use a "+" ?

**Comment by mcarrano** [comment]
Yes, @matthewcarleton , I just created this mockup quickly and typed in a lower case "v". But the actual design should use a caret icon. I think this is more typical than "+" and "-" but open to hear other opinions.

**Comment by kybaker** [comment]
@matthewcarleton Agree with @mcarrano the caret would keep it consistent with the rest of PF.

**Comment by zhutaoredhat** [comment]
@serenamarie125 @mcarrano I had pulled a new commit. Updated:
1.Use "Log in using" for both options.
2.Remove "Please" from the prompt.
3.Updated the orange warning icon with dark gray/black text.
4.Add "more" and "hide" button under the third party account buttons.


About title of the page should be "Login" not "Log In", I am not sure whether to update them, waiting for others feedback. 
e827659bacd20caa9d688e4933c00691_hd

I love the idea limit to a max of 4 shown on the screen about social accounts.
Thank you~

**Comment by jeperry** [comment]
Log in vs Login all depends on intent. 

**Log In** (two words) is correct if the intent is for the title to be an invitation (we are inviting the user to do something, to log in). **This usage makes the most sense to me.** 

**Login** (on word) may be acceptable if our aim is to state the purpose of the page (this is the login page) but this is writing from the system point of view and not user friendly.

I strongly favor the usage as shown in the mockup: Log in. In my opinion, there are very few user-facing places that we should ever use the term login, which is not really a word to begin with. The Usage note here perfectly sums up the debate. http://www.dictionary.com/browse/login?s=t

**Comment by mcarrano** [comment]
@zhutaoredhat Thanks for making these changes. Here are a few additional changes I'd like you to make and then hopefully we can wrap this up.

1) Regarding the title, I think if we change from Log In to Login it will look wrong since the title and the button won't match. I'm now questioning whether this title is even needed since it is followed by the instruction "Log in using your PatternFly account". @matthewcarleton and I did some brainstorming and tried to see what this would look like if we drop the title and increase the size of the instructional text a bit. See what you think.
screen shot 2018-01-05 at 4 14 44 pm
@yih-wang I would also invite you to comment as this changes your original design.

2) Thanks for changing the More button to a More v link. But when this is open, the link should change to "Less" not "Hide." 

3) For the social login buttons, I've also given some consideration to whether we should support two columns when the number goes above 4. @serenamarie125 I am going to suggest that we keep the current design as it does have the advantage of not requiring the login height to expand when viewed in web/desktop width whenever there are less than 8 social logins. This has already been implemented by @matthewcarleton . @zhutaoredhat what I would like you to do is to change 'login-page-4.png'
so it shows both the default/preferred state with 4 buttons and then the fully loaded version with 8 buttons + More. The text explanation will be updated to reflect that 4 or less is recommended, but if more than 4, buttons must be arranged in a 2 column grid and 'More' will only appear if there are more than 8. @serenamarie125 your comment about ordering buttons by usage makes sense so we will update that. @zhutaoredhat I'm also noting that this image is missing call-outs to go with the enumerated text below.

4) @matthewcarleton and I were reviewing the responsive state and decided that it does not make sense for the social login list to change to 2-columns on a mobile device because of the limited screen width. It will be implemented so the buttons just stack vertically and the user can scroll the screen if then need to see more (no More button or link is needed). Not that in this version, the title and the instructional text were also removed to economize on the height. Here's what the implementation looks like.

screen shot 2018-01-05 at 4 14 17 pm


I hope this all makes sense. If you have questions, I will be glad to do a call with you on Monday. Please just make updates to the images and I will send a separate PR to update the text to align with these design changes. Thx.

**Comment by zhutaoredhat** [comment]
Hi @mcarrano  Thanks for your feedback. For better keep consistent with other login pages, I would like not to remove the title form social account pages. At the beginning of creating mockups, we set the title on the field for providing better user experience to users, he can know where he is much more clearly in this way. Here is the other design that I removed the sub-title. Dose it make sense to you?
social

The other question is the document doesn't include "social account comes first" method. It is popular today either. shall we add it to this PR?
p37 2x

**Comment by catrobson** [comment]
@zhutaoredhat - Social account first is popular for non-enterprise use cases.  I don't think we should add this unless we start to see this become a standard for enterprise applications.

**Comment by mcarrano** [comment]
Agree with @catrobson about the social login first variation. I think you make a valid point about removing the title @zhutaoredhat . I will coordinate a meeting to discuss further.

**Comment by mcarrano** [comment]
Today @matthewcarleton @zhutaoredhat @yih-wang @amysueg and I met to review remaining issues and agree on next steps:

1. We will keep the title text, but change from "Log In" to "Log in to your account" to clarify that this is a call to action. Other instructional text (i.e. "Login in using your PatternFly account") will be removed to save space and eliminate redundancy.

2. We will not make further changes to the responsive layout at this time, although we acknowledge some of the problems raised by the KeyCloak team. I will open a new issue to investigate PF mobile login further as this should be considered with RH product branding in mind. We can take this up as follow-on work.

Feel free to comment further if I've missed anything.

**Comment by zhutaoredhat** [comment]
Hi Matt, thanks for your updating. I pull a new commit just remove the
sub-title 5 mins ago, but not change from "Log In" to "Log in to your
account".  It can be defined by customer as we discussed, Haley will update
this part to the document. Do you think it is make sense? or Update all the
pages to "Log in to your account"

Thank you,
Tao

**Comment by mcarrano** [comment]
@zhutaoredhat I would like this to be changed to "Log in to your account" with a note in the text that says that "your account" can be replaced with whatever makes sense for the application. Do you see a problem with that? I though that was what we agreed to.

**Comment by matthewcarleton** [comment]
@mcarrano @zhutaoredhat @yih-wang @amysueg I've updated the code so each section is announced by screen readers.

**Comment by zhutaoredhat** [comment]
@catrobson Thank you, +1 for social account first is popular for non-enterprise use cases.

**Comment by zhutaoredhat** [comment]
@mcarrano Very sorry, I may not make my point clearly in the meeting. I think we will meet some small problems.
1. The title is using h1 of css style currently. It is a very large font-size. It maybe responsive to two lines on mobile. Maybe use h2 will be better, but it will looks a little different.
2.For keep consistent with other log in pages, should I update them all to "Log in to your account"
Thank you~

**Comment by matthewcarleton** [comment]
@zhutaoredhat We need to keep it an h1 for accessibility/semantics but I can resize on mobile to an h3.  That ensures it is visually the right size for desktop as well.

**Comment by mcarrano** [comment]
If we can resize for mobile, does that address your concern @zhutaoredhat ? Regarding the capitalization, I think it's correct to use sentence style capitalization because this is an instruction. But @LHinson , can you give a second opinion?

**Comment by zhutaoredhat** [comment]
@mcarrano @matthewcarleton Great thanks. I will update them all tomorrow.

**Comment by mcarrano** [comment]
Spoke with @LHinson about the capitalization issue. Let's stick with headline style capitalization for this, i.e. Log In to Your Account. So no need to change other patterns that are already using this @zhutaoredhat .

**Comment by matthewcarleton** [comment]
I've updated the test page to show the full list of social accounts (Git, Dropbox, Fedora, Skype)

**Comment by mcarrano** [comment]
@serenamarie125 Agree that "Sign Up" should probably be "Sign up"  @zhutaoredhat can you make one more round of changes? Hopefully we are getting close :)

**Comment by zhutaoredhat** [comment]
@serenamarie125 @mcarrano @matthewcarleton Thank you all. I have updated them all and pulled the new commit.

**Comment by mcarrano** [comment]
Thanks, @zhutaoredhat There were two additional small text changes requested by @serenamarie125 above that I think you missed. Can you please make those two updates? Sorry about that. Hopefully that will be all.

**Comment by zhutaoredhat** [comment]
@mcarrano Hi,Matt. I had updated three things:
1.Updated "Sign Up" to "Sign up" in login pages
2,Updated “Resend Confirmation link”  to "Resend confirmation link"
3.Removed the "please" from the error message of server-1.png
Sorry, I am not clear which additional small text I didn't update.

**Comment by mcarrano** [comment]
Thanks, @zhutaoredhat . I think you have addressed everything. @serenamarie125 can you just confirm/approve and I will go ahead and merge.

**Comment by zhutaoredhat** [comment]
@serenamarie125 You are welcome~: )

**Pull request merged**
