### PR TITLE
chore(page title): Add unique titles for pattern Library pages

### PR DESCRIPTION
**Pull request by dabeng**
## Description
This PR is targeted to fix the [issue](https://github.com/patternfly/patternfly-org/issues/569)

## Changes

Write a list of changes this design pattern introduces

* Pages under "Pattern Library" section have their respective page title.

### CODE REVIEW

**Comment by amarie401** [comment]
@dabeng could you provide us with an updated demo staging link for this as it is currently? It'll be easier for @mcarrano and I to review the other category pages.

**Comment by amarie401** [comment]
Hmm @mcarrano so I don't think we will be able to test it how it is currently through the design repo until it gets merged, we can test on pf-org and make manual changes to the pf-design's 62 `site.md` files (through the generated repos folder) -- which I believe is what @dabeng did with the demo page that he gave us (except he only updated the first two categories for testing/demo purposes). 

Since this is simply adding a title to each one then I think that we will fine with a cross reference review to just make sure the titles added match their respective pages. Everything looks good to me in that case.

**Comment by mcarrano** [comment]
OK. In that case I will go ahead and merge @amarie401 . We should both check the site once it rebuilds to make sure everything is OK.

So I think what this means is that the Title now needs to be added to the site.md file for all contributions. Is that right @dabeng @amarie401 ? If that's the case, I will need to add to the design contribution instructions.

**Comment by amarie401** [comment]
Yes you're correct @mcarrano going forward contributions will now need to include a title.

**Pull request merged**
