### PR TITLE
Pagination Updates

### PR DESCRIPTION
**Pull request by wrnkld**
This pull request addresses PTNFLY-2161, including updated content view images and updated recommendations around no data to display and disabled controls.

### CODE REVIEW

**Comment by wrnkld** [comment]
Hello @LHinson @catrobson @maryclarke @jeperry @serenamarie125 @mcarrano - this pull request is ready for review.

**Comment by maryclarke** [comment]
looks good to me @wrnkld, just one small question around whether we need the dividing bar between the number selected and the kebab menu

**Comment by wrnkld** [comment]
@maryclarke you're right. we probably don't need the divider.

**Comment by wrnkld** [comment]
@LHinson @catrobson @maryclarke @jeperry @serenamarie125 @mcarrano one thing i would like feedback on: in the cafe testing, vince found that 4 of the 12 users did not know the checkbox in the column header could be used to quickly select the rows in view. he is recommending a tooltip on the checkbox.

**Comment by LHinson** [comment]
+1 @wrnkld I think that tooltip makes sense!

**Comment by mcarrano** [comment]
Looks good to me @wrnkld . Agree with others that the vertical separator is not needed and that a tooltip should be added when the user hovers over the select all checkbox.  Recommend that this says something like "Select all on this page" to differentiate from global select all.

**Comment by LHinson** [comment]
@wrnkld I've heard the design for this pagination has opened back up based on recent reviews although I'm not quite aware of the extent given I don't see comments on this PR. 

Let's merge this PR and sync on what additional stories need to be added to the backlog to account for this work. I don't think the story for pagination in the current sprint covers the recent change in scope. 

@wrnkld additionally, let's discuss whether or not you have the bandwidth to pull it into this sprint along with your other stories. 

FYI @maryclarke @catrobson @serenamarie125 @jeperry  @mcarrano

**Comment by wrnkld** [comment]
ok thank you @LHinson.

**Pull request merged**
