### PR TITLE
Fix UI issues related to #636 has been merged 

### PR DESCRIPTION
**Pull request by nding-anges**
## Description
* Fix tow UI issues after #636 has been merged : 
   1) Table is missing 
   2) Images of sort icon  are repeated. 
* See more detail on Patternfly http://www.patternfly.org/pattern-library/forms-and-controls/sort/#design

## Changes

* Added {:.table .table-striped .table-bordered} to the end 
* Delete code for insert image in the Table.

### CODE REVIEW

**Comment by nding-anges** [comment]
@mcarrano @jennyhaines  I saw two UI issues in Patternfly after we merged the PR this morning : 
1) Table is missing 
2) image of sort icons is repeated. See detail: [http://www.patternfly.org/pattern-library/forms-and-controls/sort/#design]
Please help me to review markdown code . I think this issue could not be funded on preview of .MD file. Thanks a lot.

**Comment by jennyhaines** [comment]
@nding-anges @mcarrano Sorry- I should have also looked at the code while reviewing previously... I usually just use the preview functionality when reviewing PRs like that. I agree with your changes. I compared the code to our icons.md file, and see that the _{:.table .table-striped .table-bordered}_ is correct, and that we only pull in the icons with the syntax of _<span class="pficon pficon-nameoficon">_ rather than using PNGs.

**Comment by mcarrano** [comment]
Thanks for reviewing @jennyhaines. I am going to merge this one and hope that these changes correct the problem. Thanks also for catching this @nding-anges .

**Comment by nding-anges** [comment]
Hi @mcarrano @jennyhaines I just check on Patternfly ,the page didn't be changed and issue was still there. I am checking again but have not idea for the moment. Is anyone know the reason and can help me for double check? thanks!

**Comment by jennyhaines** [comment]
Something that I've noticed is that sometimes there is a long lag between the merging, and when the updates show up on the website. Amiee and I noticed this before when we were updating the larger icons table. @amarie401 - do you have any suggestions for us on what we can do to make this merged PR show up on the website? Thank you!!

**Comment by nding-anges** [comment]
Thanks!@jennyhaines @amarie401  Ok, I'm waiting for a moment.

**Comment by nding-anges** [comment]
The page looks good now, thank for all of you. @jennyhaines @mcarrano

**Pull request merged**
